---
include:
  # Prospector Dongle with YADS display
  - board: xiao_ble
    shield: corne_dongle dongle_screen
    artifact-name: dongle

  # Left half as peripheral (override default central role)
  - board: nice_nano
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: left

  # Right half as peripheral (default)
  - board: nice_nano
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: right

  # Settings reset for nice_nano
  - board: nice_nano
    shield: settings_reset
    artifact-name: peripheral_reset

  # Settings reset for XIAO dongle
  - board: xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
