include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
    artifact-name: left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
    artifact-name: right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset
