---
include:
  - board: nice_nano
    shield: corne_left
    artifact-name: left_central

  - board: nice_nano
    shield: corne_right
    artifact-name: right_peripheral

  - board: nice_nano
    shield: settings_reset
    artifact-name: reset_settings
