---
include:
  # Prospector Dongle with YADS display + ZMK Studio
  - board: xiao_ble
    shield: corne_dongle_xiao dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: xiao_corne_dongle_yads

  # Left half as peripheral (when using dongle)
  - board: nice_nano
    shield: corne_left_peripheral
    artifact-name: nice_corne_left_peripheral

  # Right half as peripheral
  - board: nice_nano
    shield: corne_right
    artifact-name: nice_corne_right_peripheral

  # Settings reset for nice_nano
  - board: nice_nano
    shield: settings_reset
    artifact-name: nice_nano_settings_reset

  # Settings reset for XIAO dongle
  - board: xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
